FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiamos los proyectos y restauramos paquetes
COPY *.sln .
COPY MarketPlace.Host/*.csproj ./MarketPlace.Host/
COPY MarketPlace.Application/*.csproj ./MarketPlace.Application/
COPY MarketPlace.Infrastructure/*.csproj ./MarketPlace.Infrastructure/
COPY MarketPlace.Domain/*.csproj ./MarketPlace.Domain/

RUN dotnet restore

# Copiamos todo el código
COPY . .

# Publicamos en modo Release
RUN dotnet publish src/MarketPlace.Host/MarketPlace.Host.csproj \
    -c Release -o /app/publish /p:UseAppHost=false

# -----------------------------
# 2️⃣ Runtime stage
# -----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Puerto que exponemos en contenedor
EXPOSE 8080

# Copiamos desde el build stage
COPY --from=build /app/publish .

# Ejecutamos la API en Production
ENTRYPOINT ["dotnet", "MarketPlace.Host.dll"]